apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus
  namespace: kube-system
  labels:
    app: prometheus-server
spec:
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
      - name: prometheus-server
        image: rohitraut3366/prometheus:latest
