- hosts: tag_Name_ec2-webserver 
  vars_files: database_config_variables
  roles:  
    - role: nginx-wordpress
      vars:
        - database: "{{ database }}"
        - database_user: "{{ database_user }}"
        - database_user_password: "{{ database_password }}"
        - hostname: "{{ hostname }}"
