pipeline{
    agent { 
        label "packer"
    }
    parameters {
        string(name: 'ASG_DESIRED_SIZE', description: 'Desired Number of instances in auto scaling group')
        string(name: 'ASG_MAX_SIZE',description: "Maximum size of auto scaling group")
        string(name: 'ASG_MIN_SIZE',description: "Minimum size of auto scaling group")
    }
    stages{
        stage("gitscm"){
            steps{
                sh "echo Build Started"
                git branch: 'master', url: 'https://github.com/rohitraut3366/terraform-packer-build.git'
            }
        }
        stage("Build remote Backend"){
            steps{
                sh "echo backend build started"
                sh "terraform -chdir=terraform-remote-state init"
                sh "terraform -chdir=terraform-remote-state plan"
                sh "terraform -chdir=terraform-remote-state apply --auto-approve"
                sh "echo backend build finish"
            }
        }
        stage("Terraform init"){
            steps{
                sh "chmod 400 packer-build/devops.pem"
                sh "terraform init"
            }
        }
        stage("Terraform Plan"){
            steps{
                sh "terraform plan"
            }
        }
        stage("Terraform Apply"){
            steps{
                sh "terraform apply --auto-approve \
                   -var asg_min_capacity=${params.ASG_MIN_SIZE} \
                   -var asg_max_capacity=${params.ASG_MAX_SIZE} \
                   -var asg_desired_capacity=${params.ASG_DESIRED_SIZE}"
            }
            post{
                success{
                    echo "executed successfully"
                }
                failure{
                    echo "execution failed"
                }
            }
        }
    }
}