pipeline{
    agent { 
        docker {
            image 'rohitraut3366/packer:v1'
            args '-v /home/rohitraut/.aws:/root/.aws'
        }
    }
    parameters {
        string(name: 'ASG_DESIRED_SIZE', description: 'Desired Number of instances in auto scaling group')
        string(name: 'ASG_MAX_SIZE',description: "Maximum size of auto scaling group")
        string(name: 'ASG_MIN_SIZE',description: "Minimum size of auto scaling group")
    }
    stages{
        stage("gitscm"){
            steps{
                sh "echo Build Started"
                git branch: 'master', url: 'https://github.com/rohitraut3366/terraform-packer-build.git'
            }
        }
        stage("Terraform init"){
            steps{
                sh "chmod 400 packer-build/devops.pem"
                sh "terraform init"
            }
        }
        stage("Terraform Plan"){
            steps{
                sh "terraform plan"
            }
        }
        stage("Terraform Apply"){
            steps{
                sh "terraform apply --auto-approve \
                   -var asg_min_capacity=${ASG_MIN_SIZE} \
                   -var asg_max_capacity=${ASG_MAX_SIZE} \
                   -var asg_desired_capacity=${ASG_DESIRED_SIZE}"
            }
            post{
                success{
                    echo "executed successfully"
                }
                failure{
                    echo "execution failed"
                }
            }
        }
    }
}